pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }



    stages {
        stage('Test') {
            steps {
                // Get some code from a GitHub repository
                sh 'node --version'
            }

        }
    }
}
